### ISSUE TITLE
Not working open with chrome on windows Sublime Text 3

### ISSUE THREAD

**Issue by nramirez** [adampresley/sublime-view-in-browser#31]
Hello,
I have sublime Text 3 and I can't edit the Browser.sublime-settings file. I set chrome as my default browser, but as I couldn't change "%Local AppData%" to my actual route "C:\Program Files (x86)" It isn't working.

How can I go through this?

Thanks in advance.

PS: It's working with the other browsers, and I'm using windows 8.1.

**Comment by mickeo4** [comment]
This is a really old post but for anyone trying to get this working, this is how I got around it.  If u want to use chrome then you set up your user preferences file as mentioned above (changing the default path to chrome to be something like C:/Program Files (x86)/Google/Chrome/Application/chrome.exe and the selectedBrowser at the bottom to 'chrome').

In sublime under 'Preferences->PackageSettings->View in Browser->Settings-Default', change the bottom section from "browser": "firefox" to "browser": "chrome64"

**Comment by graphitivity** [comment]
Gwad i tried so many things and almost pulled out all the hair on my head but Yay! finally this worked for me... thanks mickeo4.

**Comment by captaininbox** [comment]
won't let me edit "Settings-Default", if I browser to the folder where it claims to be stored it's not there / right click > open containing folder takes to c:/.
is this a windows10 thing?

**Comment by Jack-Dandy** [comment]
Dangit.. Still not working for me.
I tried everything detailed here.

Made the following 2 files in the Packages\User folder:




Made

**Comment by dahol** [comment]
@captaininbox Thanks, that solution worked for me :)

{
"browser": "chrome64"
}

in "View In Browser.sublime-settings"-file.

**Comment by korutx** [comment]
1. Ctrl + `
2. I found the following error: 
 ```
File "C:\Program Files (x86)\sublime\Data\Packages\View In Browser\ViewInBrowserCommand.py", line 137, in getWindowsUserShellFolders
    return_dict[name] = value.encode("ascii")
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 26: ordinal not in range(128) 
```
3.  I opened the file ViewInBrowserCommand.py line 137, I changed:
`value.encode("ascii")` for `value.encode("utf-8")`

It worked!

**Comment by PGFracing** [comment]
Using MAC

and I changed the default to firefox, safari, chrome, tried them all nothing happens, it doesn't open a browser any suggestions?
