### ISSUE TITLE
Google Chrome Canary Compatibility

### ISSUE THREAD

**Issue by hollycunningham** [adampresley/sublime-view-in-browser#43]
Is this an accurate solution for adding compatibility with Chrome Canary?

{
    "supportedBrowsers": {
        "canary": [
            {
            "osname": "posix",
            "platform": "darwin",
            "command": "open -a '/Applications/Google Chrome Canary.app'"
            }
        ]
    },

"selectedBrowser": "canary"
}

(Apologies for the bad formatting.)

Source: https://github.com/sapegin/dotfiles/blob/master/sublime/User/View%20In%20Browser.sublime-settings

**Comment by adampresley** [comment]
In the most recent version of View In Browser the format would look like this.

```json
{
   "posix": {
      "darwin": {
         "canary": "open -a '/Applications/Google Chrome Canary.app'"
      }
   },

   "browser": "canary"
}
```

**Comment by hollycunningham** [comment]
Yes, works like a charm! Thanks for the useful package.
