### ISSUE TITLE
Fails to open URL containing spaces on local server

### ISSUE THREAD

**Issue by krypsin** [adampresley/sublime-view-in-browser#44]
Seems like spaces need to be converted to *%20* in order to launch the correct file in a local server.

When I hit CTRL+ALT+V, multiple Firefox tabs open.
- Tab one is the server path all the way up to the first space
- Tab 2 is what is in the URL after the first space
- Tab 3 is what is in the URL after the second space
- So on

Here's what my .sublime-project file contains:

	{
		"folders":
		[
			{
				"follow_symlinks": true,
				"path": "P:\\Operations\\Design\\Email designs"
			}
		],
		"settings": {
			"sublime-view-in-browser": {
				"baseUrl": "http://griffin.gnm.office/flexshare/gingernut_share/Operations/Design/Email%20designs",
				"basePath": "P:\\Operations\\Design\\Email designs"
			}
		}
	}

Open hitting CTRL+ALT+V to open
`P:/Operations/Design/Email designs/Pet Super Market/GNM_2250/html/d2/Final-design-2.html`
I get these tabs opened:
![image](https://cloud.githubusercontent.com/assets/8135396/6165751/2c37e8c8-b2a2-11e4-83c9-9e74f960bf25.png)
So you can see it gets cut off after **Pet**, and I cannot add in *%20* myself as that would mean renaming the folder (multiple people work in these folders, so not an option).

Am using Sublime Text 3, Windows 7 SP1 64-bit. Console shows this:
	View In Browser plugin v2.0.0, Python 3
	C:\Program Files (x86)\Mozilla Firefox\firefox.exe -new-tab http://griffin.gnm.office/flexshare/gingernut_share/Operations/Design/Email%20designs/Pet Super Market/GNM_2250/html/d2/Final-design-2.html

**Comment by adampresley** [comment]
The latest commit replaces spaces, and parenthesis. This *should* be addressed. My tests showed positive results.
