### ISSUE TITLE
Option (or secondary key binding) to open containing folder

### ISSUE THREAD

**Issue by megadr01d** [adampresley/sublime-view-in-browser#46]
View In Browser works great but I can't find a way to change the code to open the containing folder instead of the open file. I'm using it for local server testing and I have folder structures like these:

~~~
project/path/to/index.php
               /file.md
~~~

So, let's say I'm editing `project/path/to/file.md`. I'd like to open `localhost/path/to/` (which will trigger the `index.php`) instead of `localhost/path/to/file.md` (which will just reveal the `.md` file in Finder). What better way to preview my Markdown files than to use my original website style, instead of having to install a separate Markdown preview plugin?

**Comment by adampresley** [comment]
Honestly using a Markdown plugin for previewing Markdown files is probably best. There are several decent options out there. I use https://github.com/revolunet/sublimetext-markdown-preview
