### ISSUE TITLE
Fails silently on mac if brackets present in file path

### ISSUE THREAD

**Issue by barredespace** [adampresley/sublime-view-in-browser#52]
Tested with Chrome, Safari, Firefox

**Comment by chongyuan** [comment]
me too

**Comment by adampresley** [comment]
Does the Sublime console report any errors at all? When you say "brackets" you are speaking of the literal character, and not the product, yes?

**Comment by barredespace** [comment]
Yes, the literal character. Actually, I mean "parenthesis" to be sure.
And no, no error :
```
View In Browser plugin v2.0.0, Python 3
open -a "/Applications/Google Chrome.app" file:////Users/Pac/Sites/superolol.com(test)/clown.html
```
And nothing opens, nor happens.

**Comment by adampresley** [comment]
I'll have to craft a test and see what I can find. Thanks for the information.

**Comment by adampresley** [comment]
I have verified the issue, and I believe I have a fix. Coming shortly.
