### ISSUE TITLE
Can't change browser

### ISSUE THREAD

**Issue by brandonmcconnell** [adampresley/sublime-view-in-browser#53]
I installed *View in Browser* and changed the user settings to view in Chrome, closed and reopened Sublime, but all my files still open in Firefox.

I used your instructions here: https://github.com/adampresley/sublime-view-in-browser/wiki/Configuring-Browsers

**Comment by HJThompson** [comment]
same, windows and linux

**Comment by NDanielle** [comment]
I've also confirmed that these steps do not work.

**Comment by HJThompson** [comment]
do this NDanielle and anyone else http://www.c-sharpcorner.com/UploadFile/370e35/how-to-configure-sublime-text-to-open-html-file-in-chrome-on/

**Comment by mitchell271** [comment]
Similar issue. In Win10, Chrome won't open, but firefox and edge will. Works perfectly on my Mac running the most recent public release.

**Comment by cohdee** [comment]
I was able to get mine working with "browser": "chrome64" instead of "browser": "chrome" in the View In Browser user settings. Hope this helps!

**Comment by Jolva** [comment]
Yes, per above, changing to "chome64" did the trick on Windows 8.1 as well.

**Comment by josslzr** [comment]
You can use CTRL+ALT+C from sublime text and it will open the file on chrome if it does not just go to preferences/browse packages and look for a folder called View In Browser then if you are using windows open a file called Default (Windows).sublime-keymap there you will find commands to open files on safari, IE, firefox, and chrome. Change this { "keys": [ "ctrl+alt+c" ], "command": "view_in_browser", "args": { "browser": "**chrome**" } }, to { "keys": [ "ctrl+alt+c" ], "command": "view_in_browser", "args": { "browser": "**chrome64**" } }, if you are using 64 bits. If you need to change the route for chrome just open a file called View In Browser and make sure the route is correct. Hope It helps
