### ISSUE TITLE
View in Browser package isn't appearing 

### ISSUE THREAD

**Issue by jwolfe890** [adampresley/sublime-view-in-browser#54]
I've already installed package control, but when I search for View in Browser it doesn't appear. I took a screen shot of my screen. I'd really appreciate any help on this because I've searched all over google and youtube and can't find an answer. Thank you! 
<img width="1151" alt="screen shot 2015-10-14 at 4 31 29 pm" src="https://cloud.githubusercontent.com/assets/13284468/10496935/21698244-7291-11e5-8309-812e20ebdd05.png">

**Comment by adampresley** [comment]
What happens when you press CTRL+OPTION+V?

**Comment by jwolfe890** [comment]
nothing. 

i figured it out though. i wasn't going through package control properly to find the View in Browser app. 

thanks for your response though :)
